server:
  port: 8080

spring:
  application:
    name: aks-spring-demo

app:
  message: ${APP_MESSAGE:Hello from Spring Boot on Azure Kubernetes Service - Dhaval}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
