apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: aks-spring-demo
    newName: aks-spring-demo
    newTag: "20260609-152940"
patches:
  - target:
      kind: Deployment
      name: aks-spring-demo
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - path: ingress-patch.yaml
