apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: aks-spring-demo
    newName: aksdemodemo656256.azurecr.io/aks-spring-demo
    newTag: "20260609-160839"
