apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-spring-demo
  namespace: aks-demo
  labels:
    app: aks-spring-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aks-spring-demo
  template:
    metadata:
      labels:
        app: aks-spring-demo
    spec:
      containers:
        - name: app
          image: aks-spring-demo:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: aks-spring-demo-config
                  key: APP_MESSAGE
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
