apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aks-demo
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: aks-spring-demo
    newName: aks-spring-demo
    newTag: "1.0.0"
